/*
 * @file           sfw200015.h
 * @filetype       c header file
 * @brief          내부연동 tpcall async N-tx reply 처리
 * @author         dongmin
 * @version
 * @dep-header
 * @history
 *    Version:   Name  :    Date   :     Reference :       Desciption    :
 *    --------   ------     --------     -----------     -------------------------------------------
 *    VER1.00  : dongmin :  20180403   :  proframe 구축 :  신규 개발
 * 
 */
// Generated by Proframe 5.0
#ifndef _sfw200015_H_
#define _sfw200015_H_

#include <pfmCommon.h>
#include <pfmUtility.h>
#include <pfmLogMacro.h>
#include <pfmComBuf.h>
#include <pfmDbio.h>
#include <pfmServiceModuleFrame.h>
#include <pfmBatchModuleProcess.h>
#include <pfmVarray.h>
#include <pfmFileIOFrame.h>
#include <pfmMapperApi.h>
#include <prlcall.h>
#include <pfmBatchFrame.h>
#include <pfmBatchJobTable.h>

// Includes Structs
#include <pfmMappergetReplyInfo.h> // getReplyInfo
#include <pfmMappersfw200001_in.h> // sfw200001_in
#include <pfmMappersfw200001_out.h> // sfw200001_out
#include <pfmMappersfw200002_in.h> // 사원정보조회_in
#include <pfmMappersfw200002_out.h> // 사원정보조회_out

#if defined (__cplusplus)
   extern "C"
   {
#endif
// ComBuf Data

// Context Data
typedef struct {
    sfw200001_in *input; /* sfw200001_in(sfw200001_in) */
    sfw200001_out *output; /* sfw200001_out(sfw200001_out) */
} sfw200015Context;

// Functions Pre-Declaration
static long a100_init_proc(sfw200015Context *context); // 초기값설정
static long b100_input_check(sfw200015Context *context); // 입력값검증
static long c100_main_proc(sfw200015Context *context); // 메인처리
static long c110_main_proc(sfw200015Context *context); // 사원정보조회
static long d100_output_proc(sfw200015Context *context); // 출력처리

#define INPUT  (context->input)
#define OUTPUT (context->output)
// Virtual Functions Pre-Declaration
#if defined (__cplusplus)
   }
#endif

#endif /* _sfw200015_H_ */
